project:
  type: website
output-dir: docs

website:
  title: "Math 313: Survey Design and Sampling"
  sidebar:
    style: "docked"
    collapse-level: 1
    contents:
      - text: "Home"
        href: index.html
      - text: "About"
        href: about.html

      - section: "Week 1"
        contents:
          - text: "Lecture 1"
            href: Day1.html
          - text: "Lecture 2"
            href: Day2.html
          - text: "Lecture 3"
            href: Day3.html

      - section: "Week 2"
        contents:
          - text: "Lecture 4"
            href: Day4.html
          - text: "Lecture 5"
            href: Day5.html
          - text: "Lecture 6"
            href: Day6.html

      - section: "Week 3"
        contents:
          - text: "Lecture 7"
            href: Day7.html
          - text: "Lecture 8"
            href: Day8.html
          - text: "Lecture 9"
            href: Day9.html

      - section: "Week 4"
        contents:
          - text: "Lecture 10"
            href: Day10.html
          - text: "Lecture 11"
            href: Day11.html
          - text: "Lecture 12"
            href: Day12.html

      - section: "Week 5"
        contents:
          - text: "Lecture 13"
            href: Day13.html
          - text: "Lecture 14"
            href: Day14.html
          - text: "Lecture 15"
            href: Day15.html

      - section: "Week 6"
        contents:
          - text: "Lecture 16"
            href: Day16.html
          - text: "Lecture 17"
            href: Day17.html
          - text: "Lecture 19"
            href: Day19.html

      - section: "Week 7"
        contents:
          - text: "Lecture 20"
            href: Day20.html
          - text: "Lecture 21"
            href: Day21.html
          - text: "Lecture 22"
            href: Day22.html

      - section: "Week 8"
        contents:
          - text: "Lecture 23"
            href: Day23.html
          - text: "Lecture 24"
            href: Day24.html
          - text: "Lecture 25"
            href: Day25.html

      - section: "Week 9"
        contents:
          - text: "Lecture 26"
            href: Day26.html
          - text: "Lecture 27"
            href: Day27.html
          - text: "Lecture 28"
            href: Day28.html

      - section: "Week 10"
        contents:
          - text: "Lecture 29"
            href: Day29.html
          - text: "Lecture 30"
            href: Day30.html
          - text: "Lecture 31"
            href: Day31.html

      - section: "Week 11"
        contents:
          - text: "Lecture 32"
            href: Day32.html
          - text: "Lecture 33"
            href: Day33.html
          - text: "Lecture 34"
            href: Day34.html

      - section: "Week 12"
        contents:
          - text: "Lecture 35"
            href: Day35.html
          - text: "Lecture 36"
            href: Day36.html
          - text: "Lecture 37"
            href: Day37.html

      - section: "Week 13"
        contents:
          - text: "Lecture 39"
            href: Day39.html
          - text: "Lecture 40"
            href: Day40.html
          - text: "Lecture 41"
            href: Day41.html

      - section: "Week 14"
        contents:
          - text: "Lecture 42"
            href: Day42.html

      - section: "Tutorials"
        contents:
          - text: "R and RStudio"
            href: RandRStudio.html

      - section: "Guidelines"
        contents:
          - text: "Lab Report Guidelines"
            href: LabReportGuidelines.html


format:
  html:
    highlight-style: arrow
    fontsize: 1.1em
    code-overflow: wrap
    theme:
      light: [lux, theme-light.scss]
      dark: [superhero, theme-dark.scss]
    css: styles.css
    toc: true
    page-layout: full
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true 
    
filters:
  - shinylive
  - webr

page-footer: 
  left: |
    <span class="faux-block">&#169; 2024 Deepak Bastola</span>
  right: |
    <span class="faux-block"><a href="https://github.com/deepbas/">View source on GitHub</a></span>

execute:
  new_session: true
  before_chapter_script: common.R
  freeze: true
  eval: true
  echo: true
  warning: false

